### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by PabloC** [nickjj/docker-rails-example#2]
Any idea on how to fix this 2 warnings?

web_1        | Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.3). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.3`.

On this, I suggest to install latest bundler in the Dockerfile before running bundle install.

worker_1     | WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
worker_1     |       minitest (>= 5.1)
worker_1     |       Available/installed versions of this gem:
worker_1     |       - 5.14.2
worker_1     |       - 5.13.0
worker_1     |       rake (>= 0.8.7)
worker_1     |       Available/installed versions of this gem:
worker_1     |       - 13.0.3
worker_1     |       - 13.0.1
worker_1     | WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
worker_1     | Please report a bug if this causes problems.

I don't know whay the worker service fire this warnings. Any idea?

Tks!

**Comment by nickjj** [comment]
I've fixed the bundler warning on the main branch, https://github.com/nickjj/docker-rails-example/commit/86063984759d0f8dd0fd256aa462b9de6363227a covers the details on why it happened.

I'd prefer to keep bundler's version linked to whatever version that comes with the Ruby version being used to keep things predictable. Bundler releases happen independently of Ruby and having to always keep bundler in sync with the latest version means you could end up with builds that change just for the sake of updating a patch release of bundler.

The other warning is a bit more tricky. I tried a bunch of things and I'm not sure how to fix it in a way that works with Docker. It's weird because the available version is actually what's installed, but the warning says they are different. On the bright side it's not causing any issues AFAIK.

**Comment by PabloC** [comment]
Thank you Nick for fixing the first and also teaching what's the problem. And apologies for mentioning 2 issues on the same issue. Yes, the second is not giving problems. I'll study on how to fix and come back to you.

**Comment by nickjj** [comment]
If you want to open a new issue specific to the gem warning we can keep it open with a help wanted tag.
