### ISSUE TITLE
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by PabloC** [nickjj/docker-rails-example#3]
Could anyone help us to fix this warning? No idea on how to do it.

```
worker_1     | WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
worker_1     |       minitest (>= 5.1)
worker_1     |       Available/installed versions of this gem:
worker_1     |       - 5.14.3
worker_1     |       - 5.13.0
worker_1     |       racc (~> 1.4)
worker_1     |       Available/installed versions of this gem:
worker_1     |       - 1.5.2
worker_1     |       - 1.4.16
worker_1     |       rake (>= 0.8.7)
worker_1     |       Available/installed versions of this gem:
worker_1     |       - 13.0.3
worker_1     |       - 13.0.1
worker_1     | WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
worker_1     | Please report a bug if this causes problems.
```

**Comment by nickjj** [comment]
I tried a bunch of things and I'm not sure how to fix it in a way that works with Docker.

It's weird because:

- It only affects the worker which uses the same exact bundle installed gems as the web and cable containers
- If you exec into the worker container and goto `/usr/local/bundle/gems` there's only 1 copy of each of those gems installed (the newer version)

In the end this isn't causing things to not run, but it would be nice to get rid of the warning.

**Comment by nickjj** [comment]
This ended up being resolved by https://github.com/nickjj/docker-rails-example/commit/ed7e99c52ab35e4d0143373342bafb14a8183319. Turns out not using `bundle exec sidekiq` caused these warnings.
