### ISSUE TITLE
Set env variables via ./run

### ISSUE THREAD

**Issue by alsted** [nickjj/docker-rails-example#51]
I can't really see a way to do do something as:

./run cmd SOME_ENV_TO_SET=Y bin/rails db:seed

Where SOME_ENV_TO_SET is something for deciding when to do one or the other for a given environment. db:seed is just an example for what im working on right now for seeding development machines once in a blue moon. 

I dont wish to add them to .env file as it is really one time operation for most machines. 

I have considered adding to ./run and call "_dc -e  ..."  is that the preferred way to add such a feature?

**Comment by nickjj** [comment]
Hi,

You can pass them to Docker with `-e` one at a time as you suggested if you don't want to put them into the `.env` file. That's just how Docker works, you need to pass the env var into the container in some way.

Personally I would add it to the `.env` file since it's required for your app to function.

**Comment by alsted** [comment]
Thanks.
